package install;

import java.io.File;
import java.io.InputStream;
import java.net.URISyntaxException;
import javax.swing.JOptionPane;

/**
 *
 * @author JosepOriol
 */
public class Principal extends javax.swing.JFrame {

    private String separator, name, dir, os, home;
    private File installDir;
    private InputStream inputZip;
    private fileCopy copiador;
    private boolean ready;

    private void removeRecursively(File f) {
        if (f.isDirectory()) {
            for (File ff : f.listFiles()) {
                removeRecursively(ff);
            }
        } else {
            f.delete();
        }
    }

    public enum osType {

        WINDOWS, LINUX, MAC, NS
    }
    private osType targetOs = osType.NS;

    /**
     * Creates new form Principal
     */
    public Principal() throws URISyntaxException {
        initComponents();

        ready = false;
        separator = System.getProperty("file.separator");
        os = System.getProperty("os.name").toLowerCase();
        name = System.getProperty("user.name");
        dir = System.getProperty("user.dir");
        home = System.getProperty("user.home");

        inputZip = this.getClass().getResourceAsStream("/" + "files.zip");
        if (inputZip == null) {
            addText("No existeix l'arxiu files.zip");
        } else {
            ready = true;
        }

        jTextArea1.setText("Hello " + name);

        if (os.contains("windows")) {
            installDir = new File(home + separator + "AppData" + separator + "Roaming" + separator + ".minecraft");
            targetOs = osType.WINDOWS;
            ready = true;
        } else if (os.contains("linux")) {
            installDir = new File(home + separator + ".minecraft");
            targetOs = osType.LINUX;
            ready = true;
        } else if (os.contains("mac")) {
            installDir = new File(home + separator + "Library" + separator + "Application Support" + separator + "minecraft");
            targetOs = osType.MAC;
            ready = true;
        } else {
            addText("Your operative system is not supported");
        }
        //proves
        installDir = new File(dir + separator + "penes");
        if (installDir.exists()) {
            System.out.println("existeix");
        } else {
            System.out.println("no existeix");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jProgressBar1 = new javax.swing.JProgressBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        jButton1.setText("Install Minecraft");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setToolTipText("");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Object[] options = {"No",
            "Yes",};
        int opt = JOptionPane.showOptionDialog(this,
                "Do you really want to exit?",
                "Minecraft Installer",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.CLOSED_OPTION,
                null,
                options,
                options[0]);
        if (opt == 1) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (ready) {
            if (installDir.exists()) {
                Object[] options = {"No",
                    "Yes",};
                int opt = JOptionPane.showOptionDialog(this,
                        "Installation folder already exists, you want to remove it and continue the installation?",
                        "Minecraft Installer",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.CLOSED_OPTION,
                        null,
                        options,
                        options[1]);
                if (opt == 1) {
                    removeRecursively(installDir);
                    installDir.mkdir();
                    copiador = new fileCopy(installDir, inputZip, jProgressBar1, separator);
                    Thread t = new Thread(copiador);
                    t.start();
                }
            } else {
                installDir.mkdir();
                copiador = new fileCopy(installDir, inputZip, jProgressBar1, separator);
                Thread t = new Thread(copiador);
                t.start();
            }
        } else {
            addText("Your system is not ready for installation");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;










                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new Principal().setVisible(true);
                } catch (URISyntaxException ex) {
                    System.err.println("ERROR Creating the form" + ex.getMessage());
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    public static void addText(String message) {
        jTextArea1.setText(jTextArea1.getText() + "\n" + message);
    }
}
